# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Backend Install Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Backend Build
      run: npm run build --if-present
      working-directory: ./backend

    # Install dependencies
    - name: Install Dependencies
      run: npm ci
      working-directory: ./frontend
      
      # Update Browserslist to avoid outdated warnings
    - name: Update Browserslist
      run: npx update-browserslist-db@latest
      working-directory: ./frontend
      
      # Run ESLint to catch any linting errors
    - name: Run ESLint
      run: npm run lint --if-present
      working-directory: ./frontend

      # Build the project with CI set to false to prevent treating warnings as errors
    - name: Build the project
      run: npm run build --if-present
      working-directory: ./frontend
      env:
        CI: false
    #- run: npm test
     # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: npm run deploy
      working-directory: ./frontend

      # Configure git user for GitHub Pages deployment
    - name: Set GitHub Pages Commit Author
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
